# Tên chương trình thực thi
TARGET = main

# Thư mục hứa header và source
HEADER_DIR = inc
SOURCE_DIR = src
BINARY_DIR = build

# Các tệp nguồn và tệp object tương ứng
SOURCES = $(wildcard $(SOURCE_DIR)*.c)
